# Generated by Django 3.1.1 on 2020-09-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hot100Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.BigIntegerField()),
                ('song_name', models.CharField(max_length=50)),
                ('artists', models.CharField(max_length=50)),
                ('peak_rank', models.BigIntegerField()),
                ('weeks_on_chart', models.BigIntegerField()),
                ('rank_last_week', models.BigIntegerField()),
            ],
        ),
    ]
