# Generated by Django 3.1.3 on 2020-11-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SongsInfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
